package com.brogames.bro.objecttypes;

public class ObjectType {

	// WORLD
	public static final int GRASS = 121;
	public static final int HIGH_GRASS = 122;
	public static final int BUSH = 301;
	public static final int ROCK = 151;
	public static final int SAND = 123;
	public static final int WATER = 271;
	public static final int PALM = 241;
	public static final int PALM_TOP = 211;
	public static final int DIRT = 46;
	public static final int RUBBLE = 50;
	public static final int FOREST1 = 1;
	public static final int FOREST2 = 2;
	public static final int FOREST3 = 3;
	public static final int FOREST4 = 4;
	public static final int FOREST5 = 31;
	public static final int FOREST6 = 32;
	public static final int FOREST7 = 33;
	public static final int FOREST8 = 34;
	public static final int FOREST9 = 61;
	public static final int FOREST10 = 62;
	public static final int FOREST11 = 63;
	public static final int FOREST12 = 64;
	public static final int FOREST13 = 91;
	public static final int FOREST14 = 92;
	public static final int FOREST15 = 93;
	public static final int FOREST16 = 94;
	public static final int GRAY_PLATEAU1 = 5;
	public static final int GRAY_PLATEAU2 = 6;
	public static final int GRAY_PLATEAU3 = 7;
	public static final int GRAY_PLATEAU4 = 8;
	public static final int GRAY_PLATEAU5 = 35;
	public static final int GRAY_PLATEAU6 = 36;
	public static final int GRAY_PLATEAU7 = 37;
	public static final int GRAY_PLATEAU8 = 38;
	public static final int GRAY_PLATEAU9 = 65;
	public static final int GRAY_PLATEAU10 = 66;
	public static final int GRAY_PLATEAU11 = 67;
	public static final int GRAY_PLATEAU12 = 68;
	public static final int GRAY_PLATEAU13 = 95;
	public static final int GRAY_PLATEAU14 = 96;
	public static final int GRAY_PLATEAU15 = 97;
	public static final int GRAY_PLATEAU16 = 98;
	public static final int BROWN_PLATEAU1 = 124;
	public static final int BROWN_PLATEAU2 = 125;
	public static final int BROWN_PLATEAU3 = 126;
	public static final int BROWN_PLATEAU4 = 127;
	public static final int BROWN_PLATEAU5 = 154;
	public static final int BROWN_PLATEAU6 = 155;
	public static final int BROWN_PLATEAU7 = 156;
	public static final int BROWN_PLATEAU8 = 157;
	public static final int BROWN_PLATEAU9 = 184;
	public static final int BROWN_PLATEAU10 = 185;
	public static final int BROWN_PLATEAU11 = 186;
	public static final int BROWN_PLATEAU12 = 187;
	public static final int BROWN_PLATEAU13 = 214;
	public static final int BROWN_PLATEAU14 = 215;
	public static final int BROWN_PLATEAU15 = 216;
	public static final int BROWN_PLATEAU16 = 217;
	public static final int LAVA = 309;
	public static final int GRAY_STAIRS1 = 0;
	public static final int GRAY_STAIRS2 = 0;
	public static final int GRAY_STAIRS3 = 0;
	public static final int GRAY_STAIRS4 = 0;
	public static final int GRAY_STAIRS5 = 0;
	public static final int GRAY_STAIRS6 = 0;
	public static final int BROWN_STAIRS1 = 0;
	public static final int BROWN_STAIRS2 = 0;
	public static final int BROWN_STAIRS3 = 0;
	public static final int BROWN_STAIRS4 = 0;
	public static final int BROWN_STAIRS5 = 0;
	public static final int BROWN_STAIRS6 = 0;
	public static final int FOREST_PASSAGE = 41;
	public static final int FOREST_PASSAGE_TOP = 11;
	public static final int WRECK1 = 103;
	public static final int WRECK2 = 104;
	public static final int WRECK3 = 105;
	public static final int WRECK4 = 106;
	public static final int WRECK5 = 133;
	public static final int WRECK6 = 134;
	public static final int WRECK7 = 135;
	public static final int WRECK8 = 136;
	public static final int WRECK9 = 163;
	public static final int WRECK10 = 164;
	public static final int WRECK11 = 165;
	public static final int WRECK12 = 166;
	public static final int WRECK13 = 193;
	public static final int WRECK14 = 194;
	public static final int WRECK15 = 195;
	public static final int WRECK16 = 196;
	
	
	//Amount of tiles in enviroment.png.
	public static final int FIRST_GRID = 330; 
	
	// ITEMS
	public static final int STONE =  1+FIRST_GRID;
	public static final int STICK =  3+FIRST_GRID;
	public static final int WOODY_VINES =  2+FIRST_GRID;
	public static final int AXE =  11+FIRST_GRID;
	public static final int CURVED_STICK =  12+FIRST_GRID;
	public static final int SMALL_STONE =  15+FIRST_GRID;
	public static final int BOW =  13+FIRST_GRID;
	public static final int ARROW =  14+FIRST_GRID;
	public static final int PORTAL =  100+FIRST_GRID;
	public static final int FEATHER = 16+FIRST_GRID;
	public static final int BANANA = 4+FIRST_GRID;
	public static final int LOG = 9+FIRST_GRID;
	public static final int BOW_DRILL = 19+FIRST_GRID;
	public static final int CLAY = 99+FIRST_GRID;
	public static final int POT = 98+FIRST_GRID;
	public static final int COCONUT = 6+FIRST_GRID;
	public static final int FISHING_ROD = 28+FIRST_GRID;
	public static final int SHARP_BONE = 27+FIRST_GRID;
	public static final int SHOVEL = 97+FIRST_GRID;
	public static final int TINDER = 10+FIRST_GRID;
	public static final int MAP = 18+FIRST_GRID;
	public static final int SHOVEL_BLADE = 26+FIRST_GRID;
	public static final int OPEN_COCONUT = 7+FIRST_GRID;
	
}
